### ISSUE TITLE
error when calling get_language('any_language')

### ISSUE THREAD

**Issue by mohmehdi** [grantjenks/py-tree-sitter-languages#64]
tree-sitter has updated the Language class and how they initialize it so now it takes just one parameter. here: [example usage](https://github.com/tree-sitter/py-tree-sitter/compare/v0.22.0...v0.22.1#diff-46df084e09fb7a48733f8c5a9d0edf68b68ca8bc10ec7184734b1f601022fcd0R4)

**Comment by scanny** [comment]
Quick-fix is to downgrade to `treesitter==0.21.3`:
```bash
$ pip install -U tree-sitter==0.21.3
```

In my particular case that results in an unwelcome warning being emitted to the console at runtime:
```
.../python3.11/site-packages/tree_sitter/__init__.py:36: FutureWarning: Language(path, name) is deprecated. Use Language(ptr, name) instead.
```
but that is easily avoided in my case using the `python -Wignore ...` command-line flag.

**Comment by samuela** [comment]
FWIW an example traceback:
```
Traceback (most recent call last):
  File "/Users/samuelainsworth/dev/SWE-agent/poop.py", line 5, in <module>
    language = get_language("python")
               ^^^^^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by mohmehdi** [comment]
@samuela I don't think they are going to update this repo.

The main tree-sitter project had a [rewrite](https://github.com/grantjenks/py-tree-sitter-languages/pull/65).  

For python do this(from py-tree-sitter repo):
```
pip install tree-sitter-python
```
```python
import tree_sitter_python as tspython
from tree_sitter import Language, Parser

PY_LANGUAGE = Language(tspython.language())
```
For any other languages, you have to wait until someone makes the PyPI package for it

**Comment by aamiralidev** [comment]
I faced the same issue. I downgraded my version but not sure which one. Here are my versions of both tree-sitter & tree-sitter-languages
Name: tree-sitter
Version: 0.20.4
Name: tree-sitter-languages
Version: 1.10.2

**Comment by restlessronin** [comment]
I'm facing this issue. I downgraded to 0.21.3 as suggested in the [first response](https://github.com/grantjenks/py-tree-sitter-languages/issues/64#issuecomment-2118048885)

**Comment by thorwhalen** [comment]
Same here for:

```python
from tree_sitter_languages import get_language

TS_LANGUAGE = get_language('typescript')
```

Works for:

```
tree-sitter: 0.21.3
tree-sitter-languages: 1.10.2
```

but not for 

```
tree-sitter: 0.22  (or higher)
```

where I get

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], [line 3](vscode-notebook-cell:?execution_count=2&line=3)
      [1](vscode-notebook-cell:?execution_count=2&line=1) from tree_sitter_languages import get_language
----> [3](vscode-notebook-cell:?execution_count=2&line=3) TS_LANGUAGE = get_language('typescript')

File tree_sitter_languages/core.pyx:14, in tree_sitter_languages.core.get_language()

TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by thorwhalen** [comment]
I brought this issue to the attention of `tree-sitter` authors in this issue:

[Versions 0.22+ break tree_sitter_languages.get_language](https://github.com/tree-sitter/py-tree-sitter/issues/303)

**Comment by YesDrX** [comment]
How to load customized languages (compiled to a .so file) now?

**Comment by iamsr** [comment]
https://github.com/Goldziher/tree-sitter-language-pack

This is the latest actively maintained fork of this library.

**Comment by arkopaulhalder** [comment]
> I faced the same issue. I downgraded my version but not sure which one. Here are my versions of both tree-sitter & tree-sitter-languages Name: tree-sitter Version: 0.20.4 Name: tree-sitter-languages Version: 1.10.2

i have tried it but its showing this 

![Image](https://github.com/user-attachments/assets/278d21c8-3acd-485d-a173-722a1e3661d6)

with the req.txt being :
# API and Web Framework
flask>=2.0.0
requests>=2.31.0
python-dotenv>=1.0.0

# Code Parsing
tree-sitter==0.20.4
tree-sitter-languages==1.10.2

# Type Hints
typing-extensions>=4.9.0

# Development Tools
pytest>=7.4.0  # for testing
black>=23.12.0  # for code formatting
flake8>=7.0.0  # for linting

# Optional Dependencies
ipython>=8.12.0  # for interactive debugging
